version: "3.8"

services:
  mysql:
    build:
      context: ..
      dockerfile: docker/Dockerfile.db
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
    container_name: pureadmin-db
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pureadmin-redis
    command: redis-server --notify-keyspace-events Ex
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
